#!/bin/bash

echo "Downloading and starting VON Network"
[ -d von-network ] || git clone https://github.com/bcgov/von-network.git von-network
cd von-network
git checkout 22973513c99cc9a286a6f181ca5c5f354a4eb2ee
./manage up --wait

echo "Registering DIDs"
cd ..
while read -r seed
do
  max_retry=10
  counter=0
  until $(curl --output /dev/null --silent --fail -X POST http://localhost:9000/register -H "Content-Type: application/json" -d '{"did": null, "seed": "'${seed}'"}'); do
    printf "."
    sleep 1
    [[ counter -eq $max_retry ]] && curl -X POST http://localhost:9000/register -H "Content-Type: application/json" -d '{"did": null, "seed": "'${seed}'"}'
    (( counter++ ))
  done
done < seeds.txt
printf "\n"

echo "Starting ACA-Py agents"
docker-compose up --build --remove-orphans
